global:
  scrape_interval: 5s

scrape_configs:
  # - job_name: 'pushgateway'
  #   static_configs:
  #     - targets: ['pushgateway:9091', 'pushgateway:8092']
  - job_name: 'mqtt-exporter'
    static_configs:
      - targets: ['mqtt-exporter:9000']
